name: build-and-test
on:
  schedule:
    - cron: "*/5 * * * *"
  pull_request:
    branches:
      - main
jobs:
  first:
    name: Test cron
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: All Tests
        if: startsWith(github.head_ref, 'release') || github.event_name == 'schedule'
        run: dotnet test TestProjectCron
