name: build-pr
on:
  pull_request:
    branches:
      - main
jobs:
  first:
    name: Test pr
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: All Tests
        if: "!startsWith(github.head_ref, 'release')"
        run: dotnet test TestProject1
  notify:
    runs-on: windows-latest
    needs: first
    if: always()
    env:
      SLACK_WEBHOOK_TEST_NOTIFICATION_URL: ${{ secrets.SLACK_WEBHOOK_TEST_NOTIFICATION_URL }}
      BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    run: |
      if [ "${{ job.status }}" == "success" ]; then
        STATUS="Success ✅"
      else
        STATUS="Failure ❌"
      fi

      curl -X POST -H "Content-Type: application/json" \
        --data "{\"text\":\"Job in *${GITHUB_REPOSITORY}* finished with status: $STATUS.\n<${BUILD_URL}|View Build>\"}" \
        $SLACK_WEBHOOK_TEST_NOTIFICATION_URL
